name: 'myfirst site '
favicon: null
layout_spectrum: 0.7124298303388059
typography_spectrum: 0.01225236407481134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8153814300894737
  lightness: 0.23479423439130187
  saturation: 0.48997065145522356
  rhythmicContrast: 0.09937686705961823
purpose: []
